### ISSUE TITLE
Compilation banana-book

### ISSUE THREAD

**Issue by jrcarob** [oliviergimenez/banana-book#2]
The build tool to compile the book doesn't work properly for me. This is what I get

![Captura de pantalla 2021-09-23 a las 15 55 11](https://user-images.githubusercontent.com/45860181/134520408-9ffa14b6-44b8-4ced-8285-e2e290d189dc.png)

![Captura de pantalla 2021-09-23 a las 15 55 26](https://user-images.githubusercontent.com/45860181/134520463-7078a964-25f5-4c83-8dcb-69bd02a498d9.png)

And the execution of the index.Rmd file worked without include the other chapters.

**Comment by oliviergimenez** [comment]
Hi @jrcarob,
Thanks for getting in touch. I suspect this is a format issue when you build the book. Make sure you build with the new bookdown bs4_book as in the screenshot below. Let me know how it goes. 
Cheers,
Olivier

<img width="962" alt="Capture d’écran 2021-09-23 à 19 26 00" src="https://user-images.githubusercontent.com/12683635/134555557-790f8497-18a6-4b84-b55c-cb08b821b734.png">

**Comment by jrcarob** [comment]
Now it worked fine!! My apologies for not paying attention to the different options to built it properly. Thanks for your support!

**Comment by oliviergimenez** [comment]
No problem at all. Glad it works.
