### ISSUE TITLE
few comments on intronimble

### ISSUE THREAD

**Issue by Cyril-Milleret** [oliviergimenez/banana-book#7]
First, I wanted to say that this is very nicely written and I will recommend this chapter to anyone that starts using nimble. Find below some comments that I hope can be useful:

 **2.3**

-  It might be worth pointing out to the nimble-users [email list](https://groups.google.com/g/nimble-users) because the NIMBLE team is very helpful and usually responds very quickly! 😊
- “is distributed as (that’s the ~) as”; remove one “as”.
- “assigns a uniform between 0 and 1 as a prior distribution to the survival probability"= “assigns a uniform prior distribution between 0 and 1 to the survival probability”.
- NIMBLE also provides a summary of the MCMC using: summary(myNimbleOutput).
- “This flexibility often comes with faster convergence.” And faster runtime ([Turek et al 2020](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.3385)).
- It might be interesting to touch on the dimensions. Nimble requires to give the dimensions of the object if it is not a scalar. They can either be provided in the model code using square brackets or using the “dimensions” argument. After reading everything, I see that it comes in the section 2.7. Maybe refer to this section in the section 2.3?

**2.5**

- “Give example? Provide negative initial value for theta, or released in data < survived.” I think it is a good idea, `calculate()` will return "-Inf".  Then `survival$logProb_theta`, will also return "-Inf" which indicates that the issue comes from this node.
it also possible to reconstruct the issue in R to better understand the problem: `log(dunif(survival$theta, 0, 1 ))`. This can be useful when dealing with more complex distributions. 

`csurvival$calculate() `and `survival$calculate()` should return the same value. This is a good check when writing custom distributions as sometimes the distribution works in R but not after being compiled. If there is an issue with the custom distribution after compiling, R may even crash at this step. 

**2.7.3** 

- The downside of not doing the `calculate()`, is that you might not be able to identify issues that could help you save time in the long run. 

**2.7.4** 

- For a model that takes long to run, it might be useful to run MCMC in “bites”. This allows to check the results before the model is done running. For example we can save 80 bites each containing 250 iterations.  

```
bite.size <- 250 # number of iterations in each bite to be exported and cleared
bites <- 80 # we run 80 bites containing of 250 iterations each. 
for(nb in 1:80){
   print(nb)
   if(nb==1){# first bite 
      Cmcmc$run(bite.size)
   }
   if(nb>1){# second bite or more
      Cmcmc$run(bite.size, reset = FALSE)
   }
   this.sample <- as.matrix(Cmcmc$mvSamples)# save the 250iterations
   save(this.sample, RunTime, file=paste(”bite_”, nb, "RData”, sep=””))
}
```
Now imagine the MCMC is still running but 25 bites were finished. We can check the results of the 25 first bites (6250 iterations: 
```
bites <- 25
MCMC <- list()
for(nb in 1: bites){
  load(paste(”bite_”, nb, "RData”, sep=””))
  MCMC[[nb]] <- this.sample
}
MCMCsamples <- as.mcmc(do.call(rbind, MCMC)))
```

**2.7.9** ( suggesting a new section)

- Sometimes it might be useful to restart a model (for example to add more iterations) ran some time ago. Following [this link](https://danielturek.github.io/public/saveMCMCstate/saveMCMCstate.html), you can save and restart the model exactly where you left it.

**Comment by oliviergimenez** [comment]
Wow thank you so much @Cyril-Milleret ! I'll get to work asap 💪
